
<!DOCTYPE HTML>

<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Std&#58;&#58;terminate - C++ - W3cubDocs</title>
  
  <meta name="description" content=" std&#58;&#58;terminate() is called by the C++ runtime when exception handling fails for any of the following reasons&#58; ">
  <meta name="keywords" content="std, terminate, -, c++, cpp">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="http://docs.w3cub.com/cpp/error/terminate/">
  <link href="/favicon.png" rel="icon">
  <link type="text/css" rel="stylesheet" href="/assets/application-50364fff564ce3b6327021805f3f00e2957b441cf27f576a7dd4ff63bbc47047.css">
  <script type="text/javascript" src="/assets/application-db64bfd54ceb42be11af7995804cf4902548419ceb79d509b0b7d62c22d98e6f.js"></script>
  <script src="/json/cpp.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>


</head>

<body>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/cpp/" class="_nav-link" title="" style="margin-left:0;">C++</a></span>
  
  <nav class="_nav">
    <a href="/app/" class="_nav-link ">App</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list">
			
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<div class="_page _c">
				
<h1 id="firstHeading" class="firstHeading">std::terminate</h1>            <table class="t-dcl-begin">
<tbody> <tr class="t-dsc-header"> <th> <div>Defined in header <code><a href="../../header/exception/" title="cpp/header/exception">&lt;exception&gt;</a></code> </div>
</th> <th> </th> <th> </th> </tr> </tbody> <tbody class="t-dcl-rev"> <tr class="t-dcl t-until-cxx11"> <td> <pre data-language="cpp">void terminate();</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-until-cxx11">(until C++11)</span> </td> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">[[noreturn]] void terminate();</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr> </tbody>

</table> <p><code>std::terminate()</code> is called by the C++ runtime when exception handling fails for any of the following reasons:</p>
<div class="t-li1">
<span class="t-li">1)</span> an <a href="../../language/throw/" title="cpp/language/throw">exception is thrown</a> and not caught (it is implementation-defined whether any stack unwinding is done in this case)</div> <div class="t-li1">
<span class="t-li">2)</span> an exception is thrown during exception handling (e.g. from a destructor of some local object, or from a function that had to be called during exception handling)</div> <div class="t-li1">
<span class="t-li">3)</span> the constructor or the destructor of a static or thread-local object throws an exception</div> <div class="t-li1">
<span class="t-li">4)</span> a function registered with <code><a href="../../utility/program/atexit/" title="cpp/utility/program/atexit">std::atexit</a></code> or <code><a href="../../utility/program/at_quick_exit/" title="cpp/utility/program/at quick exit">std::at_quick_exit</a></code> throws an exception</div> <div class="t-li1">
<span class="t-li">5)</span> a <a href="../../language/noexcept_spec/" title="cpp/language/noexcept spec">noexcept specification</a> is violated (it is implementation-defined whether any stack unwinding is done in this case)</div> <div class="t-li1">
<span class="t-li">6)</span> a <a href="../../language/except_spec/" title="cpp/language/except spec">dynamic exception specification</a> is violated and the default handler for <code><a href="../unexpected/" title="cpp/error/unexpected">std::unexpected</a></code> is executed</div> <div class="t-li1">
<span class="t-li">7)</span> a non-default handler for <code><a href="../unexpected/" title="cpp/error/unexpected">std::unexpected</a></code> throws an exception that violates the previously violated dynamic exception specification, if the specification does not include <code><a href="../bad_exception/" title="cpp/error/bad exception">std::bad_exception</a></code>
</div> <div class="t-li1">
<span class="t-li">8)</span> <code>std::nested_exception::rethrow_nested</code> is called for an object that isn't holding a captured exception</div> <div class="t-li1">
<span class="t-li">9)</span> an exception is thrown from the initial function of <code><a href="../../thread/thread/" title="cpp/thread/thread">std::thread</a></code>
</div> <div class="t-li1">
<span class="t-li">10)</span> a joinable <code><a href="../../thread/thread/" title="cpp/thread/thread">std::thread</a></code> is destroyed or assigned to</div> <p><code>std::terminate()</code> may also be called directly from the program.</p>
<p><br> In any case, <code>std::terminate</code> calls the currently installed <code><a href="../terminate_handler/" title="cpp/error/terminate handler">std::terminate_handler</a></code>. The default <code><a href="../terminate_handler/" title="cpp/error/terminate handler">std::terminate_handler</a></code> calls <code><a href="../../utility/program/abort/" title="cpp/utility/program/abort">std::abort</a></code>.</p>
<table class="t-rev-begin"> <tr class="t-rev t-until-cxx11">
<td> <p>If a destructor reset the terminate handler during stack unwinding and the unwinding later led to <code>terminate</code> being called, the handler that was installed at the end of the throw expression is the one that will be called. (note: it was ambiguous whether re-throwing applied the new handlers).</p>
</td> <td><span class="t-mark-rev t-until-cxx11">(until C++11)</span></td>
</tr> <tr class="t-rev t-since-cxx17">
<td> <p>If a destructor reset the terminate handler during stack unwinding, it is unspecified which handler is called if the unwinding later led to <code>terminate</code> being called.</p>
</td> <td><span class="t-mark-rev t-since-cxx17">(since C++17)</span></td>
</tr> </table>  <h3 id="Parameters"> Parameters</h3> <p>(none).</p>
<h3 id="Return_value"> Return value</h3> <p>(none).</p>
<h3 id="Exceptions"> Exceptions</h3> <table class="t-rev-begin"> <tr class="t-rev t-until-cxx11">
<td> (none)</td> <td><span class="t-mark-rev t-until-cxx11">(until C++11)</span></td>
</tr> <tr class="t-rev t-since-cxx11">
<td> <div class="t-noexcept-inline">
<a href="../../language/noexcept_spec/" title="cpp/language/noexcept spec"><code>noexcept</code></a> specification: <div class="t-noexcept-box"><span class="t-cc"><code>noexcept</code></span></div> </div>
</td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table> <h3 id="See_also"> See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div class="t-dsc-member-div"><div><a href="../terminate_handler/" title="cpp/error/terminate handler"> <span class="t-lines"><span>terminate_handler</span></span></a></div></div> </td> <td> the type of the function called by <code>std::terminate</code> <br> <span class="t-mark">(typedef)</span>  </td>
</tr> </table>           <div class="_attribution">
  <p class="_attribution-p">
    Â© cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="http://en.cppreference.com/w/cpp/error/terminate" class="_attribution-link" target="_blank">http://en.cppreference.com/w/cpp/error/terminate</a>
  </p>
</div>

			</div>
		</div>
	</section>

	</div>
</body>
</html>
