
<!DOCTYPE HTML>

<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Exceptions - Kotlin - W3cubDocs</title>
  
  <meta name="description" content=" All exception classes in Kotlin are descendants of the class Throwable. Every exception has a message, stack trace and an optional cause. ">
  <meta name="keywords" content="exceptions, -, kotlin">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="http://docs.w3cub.com/kotlin/docs/reference/exceptions/">
  <link href="/favicon.png" rel="icon">
  <link type="text/css" rel="stylesheet" href="/assets/application-50364fff564ce3b6327021805f3f00e2957b441cf27f576a7dd4ff63bbc47047.css">
  <script type="text/javascript" src="/assets/application-db64bfd54ceb42be11af7995804cf4902548419ceb79d509b0b7d62c22d98e6f.js"></script>
  <script src="/json/kotlin.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>


</head>

<body>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/kotlin/" class="_nav-link" title="" style="margin-left:0;">Kotlin</a></span>
  
  <nav class="_nav">
    <a href="/app/" class="_nav-link ">App</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list">
			
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<div class="_page _kotlin">
				
<h1 id="exceptions">Exceptions</h1> <h2 id="exception-classes">Exception Classes</h2> <p>All exception classes in Kotlin are descendants of the class <code>Throwable</code>. Every exception has a message, stack trace and an optional cause.</p> <p>To throw an exception object, use the <em class="keyword">throw</em>-expression</p> <pre data-language="kotlin">throw MyException("Hi There!")
</pre> <p>To catch an exception, use the <em class="keyword">try</em>-expression</p> <pre data-language="kotlin">try {
    // some code
}
catch (e: SomeException) {
    // handler
}
finally {
    // optional finally block
}
</pre> <p>There may be zero or more <em class="keyword">catch</em> blocks. <em class="keyword">finally</em> blocks may be omitted. However at least one <em class="keyword">catch</em> or <em class="keyword">finally</em> block should be present.</p> <h3 id="try-is-an-expression">Try is an expression</h3> <p><em class="keyword">try</em> is an expression, i.e. it may have a return value.</p> <pre data-language="kotlin">val a: Int? = try { parseInt(input) } catch (e: NumberFormatException) { null }
</pre> <p>The returned value of a <em class="keyword">try</em>-expression is either the last expression in the <em class="keyword">try</em> block or the last expression in the <em class="keyword">catch</em> block (or blocks). Contents of the <em class="keyword">finally</em> block do not affect the result of the expression.</p> <h2 id="checked-exceptions">Checked Exceptions</h2> <p>Kotlin does not have checked exceptions. There are many reasons for this, but we will provide a simple example.</p> <p>The following is an example interface of the JDK implemented by <code>StringBuilder</code> class</p> <pre>Appendable append(CharSequence csq) throws IOException;
</pre> <p>What does this signature say? It says that every time I append a string to something (a <code>StringBuilder</code>, some kind of a log, a console, etc.) I have to catch those <code>IOExceptions</code>. Why? Because it might be performing IO (<code>Writer</code> also implements <code>Appendable</code>)… So it results into this kind of code all over the place:</p> <pre data-language="kotlin">try {
    log.append(message)
}
catch (IOException e) {
    // Must be safe
}
</pre> <p>And this is no good, see <a href="http://www.oracle.com/technetwork/java/effectivejava-136174.html" target="_blank">Effective Java</a>, Item 65: <em>Don't ignore exceptions</em>.</p> <p>Bruce Eckel says in <a href="http://www.mindview.net/Etc/Discussions/CheckedExceptions" target="_blank">Does Java need Checked Exceptions?</a>:</p> <blockquote> <p>Examination of small programs leads to the conclusion that requiring exception specifications could both enhance developer productivity and enhance code quality, but experience with large software projects suggests a different result – decreased productivity and little or no increase in code quality.</p> </blockquote> <p>Other citations of this sort:</p> <ul> <li>
<a href="http://radio-weblogs.com/0122027/stories/2003/04/01/JavasCheckedExceptionsWereAMistake.html" target="_blank">Java's checked exceptions were a mistake</a> (Rod Waldhoff)</li> <li>
<a href="http://www.artima.com/intv/handcuffs.html" target="_blank">The Trouble with Checked Exceptions</a> (Anders Hejlsberg)</li> </ul> <h2 id="the-nothing-type">The Nothing type</h2> <p><code>throw</code> is an expression in Kotlin, so you can use it, for example, as part of an Elvis expression:</p> <pre data-language="kotlin">val s = person.name ?: throw IllegalArgumentException("Name required")
</pre> <p>The type of the <code>throw</code> expression is the special type <code>Nothing</code>. The type has no values and is used to mark code locations that can never be reached. In your own code, you can use <code>Nothing</code> to mark a function that never returns:</p> <pre data-language="kotlin">fun fail(message: String): Nothing {
    throw IllegalArgumentException(message)
}
</pre> <p>When you call this function, the compiler will know that the execution doesn't continue beyond the call:</p> <pre data-language="kotlin">val s = person.name ?: fail("Name required")
println(s)     // 's' is known to be initialized at this point
</pre> <h2 id="java-interoperability">Java Interoperability</h2> <p>Please see the section on exceptions in the <a href="../java-interop/">Java Interoperability section</a> for information about Java interoperability.</p>
<div class="_attribution">
  <p class="_attribution-p">
    © 2010–2017 JetBrains s.r.o.<br>Licensed under the Apache License, Version 2.0.<br>
    <a href="https://kotlinlang.org/docs/reference/exceptions.html" class="_attribution-link" target="_blank">https://kotlinlang.org/docs/reference/exceptions.html</a>
  </p>
</div>

			</div>
		</div>
	</section>

	</div>
</body>
</html>
